/**
 * Capitals (or the city people actually mean) for countries not already in
 * the watch-list catalogue. `rank` controls map zoom: 1 = world view, 5 =
 * only when well zoomed in.
 */

export const COUNTRY_CITIES = [
  // Americas
  { id: "ottawa", name: "Ottawa", country: "Canada", tz: "America/Toronto", lat: 45.42, lon: -75.7, rank: 3, region: "Americas" },
  { id: "washington", name: "Washington", country: "USA", tz: "America/New_York", lat: 38.91, lon: -77.04, rank: 2, region: "Americas" },
  { id: "guatemala_city", name: "Guatemala City", country: "Guatemala", tz: "America/Guatemala", lat: 14.63, lon: -90.51, rank: 3, region: "Americas" },
  { id: "belmopan", name: "Belmopan", country: "Belize", tz: "America/Belize", lat: 17.25, lon: -88.77, rank: 4, region: "Americas" },
  { id: "san_salvador", name: "San Salvador", country: "El Salvador", tz: "America/El_Salvador", lat: 13.69, lon: -89.19, rank: 3, region: "Americas" },
  { id: "tegucigalpa", name: "Tegucigalpa", country: "Honduras", tz: "America/Tegucigalpa", lat: 14.07, lon: -87.19, rank: 3, region: "Americas" },
  { id: "managua", name: "Managua", country: "Nicaragua", tz: "America/Managua", lat: 12.14, lon: -86.25, rank: 3, region: "Americas" },
  { id: "san_jose_cr", name: "San José", country: "Costa Rica", tz: "America/Costa_Rica", lat: 9.93, lon: -84.08, rank: 3, region: "Americas" },
  { id: "panama_city", name: "Panama City", country: "Panama", tz: "America/Panama", lat: 8.98, lon: -79.52, rank: 3, region: "Americas" },
  { id: "havana", name: "Havana", country: "Cuba", tz: "America/Havana", lat: 23.11, lon: -82.37, rank: 2, region: "Americas" },
  { id: "kingston", name: "Kingston", country: "Jamaica", tz: "America/Jamaica", lat: 17.97, lon: -76.79, rank: 3, region: "Americas" },
  { id: "port_au_prince", name: "Port-au-Prince", country: "Haiti", tz: "America/Port-au-Prince", lat: 18.59, lon: -72.31, rank: 3, region: "Americas" },
  { id: "santo_domingo", name: "Santo Domingo", country: "Dominican Republic", tz: "America/Santo_Domingo", lat: 18.49, lon: -69.93, rank: 3, region: "Americas" },
  { id: "san_juan", name: "San Juan", country: "Puerto Rico", tz: "America/Puerto_Rico", lat: 18.47, lon: -66.11, rank: 4, region: "Americas" },
  { id: "nassau", name: "Nassau", country: "Bahamas", tz: "America/Nassau", lat: 25.06, lon: -77.35, rank: 4, region: "Americas" },
  { id: "port_of_spain", name: "Port of Spain", country: "Trinidad and Tobago", tz: "America/Port_of_Spain", lat: 10.66, lon: -61.52, rank: 4, region: "Americas" },
  { id: "bridgetown", name: "Bridgetown", country: "Barbados", tz: "America/Barbados", lat: 13.1, lon: -59.61, rank: 4, region: "Americas" },
  { id: "castries", name: "Castries", country: "Saint Lucia", tz: "America/St_Lucia", lat: 14.01, lon: -60.99, rank: 5, region: "Americas" },
  { id: "caracas", name: "Caracas", country: "Venezuela", tz: "America/Caracas", lat: 10.48, lon: -66.9, rank: 2, region: "Americas" },
  { id: "georgetown", name: "Georgetown", country: "Guyana", tz: "America/Guyana", lat: 6.8, lon: -58.16, rank: 4, region: "Americas" },
  { id: "paramaribo", name: "Paramaribo", country: "Suriname", tz: "America/Paramaribo", lat: 5.85, lon: -55.2, rank: 4, region: "Americas" },
  { id: "quito", name: "Quito", country: "Ecuador", tz: "America/Guayaquil", lat: -0.18, lon: -78.47, rank: 3, region: "Americas" },
  { id: "lima", name: "Lima", country: "Peru", tz: "America/Lima", lat: -12.05, lon: -77.04, rank: 2, region: "Americas" },
  { id: "la_paz", name: "La Paz", country: "Bolivia", tz: "America/La_Paz", lat: -16.5, lon: -68.15, rank: 3, region: "Americas" },
  { id: "asuncion", name: "Asunción", country: "Paraguay", tz: "America/Asuncion", lat: -25.26, lon: -57.58, rank: 3, region: "Americas" },
  { id: "montevideo", name: "Montevideo", country: "Uruguay", tz: "America/Montevideo", lat: -34.9, lon: -56.16, rank: 3, region: "Americas" },
  { id: "brasilia", name: "Brasília", country: "Brazil", tz: "America/Sao_Paulo", lat: -15.79, lon: -47.88, rank: 3, region: "Americas" },

  // Europe
  { id: "oslo", name: "Oslo", country: "Norway", tz: "Europe/Oslo", lat: 59.91, lon: 10.75, rank: 2, region: "Europe" },
  { id: "copenhagen", name: "Copenhagen", country: "Denmark", tz: "Europe/Copenhagen", lat: 55.68, lon: 12.57, rank: 2, region: "Europe" },
  { id: "brussels", name: "Brussels", country: "Belgium", tz: "Europe/Brussels", lat: 50.85, lon: 4.35, rank: 2, region: "Europe" },
  { id: "luxembourg", name: "Luxembourg", country: "Luxembourg", tz: "Europe/Luxembourg", lat: 49.61, lon: 6.13, rank: 4, region: "Europe" },
  { id: "bern", name: "Bern", country: "Switzerland", tz: "Europe/Zurich", lat: 46.95, lon: 7.45, rank: 3, region: "Europe" },
  { id: "zurich", name: "Zurich", country: "Switzerland", tz: "Europe/Zurich", lat: 47.38, lon: 8.54, rank: 2, region: "Europe" },
  { id: "vienna", name: "Vienna", country: "Austria", tz: "Europe/Vienna", lat: 48.21, lon: 16.37, rank: 2, region: "Europe" },
  { id: "prague", name: "Prague", country: "Czechia", tz: "Europe/Prague", lat: 50.09, lon: 14.42, rank: 2, region: "Europe" },
  { id: "budapest", name: "Budapest", country: "Hungary", tz: "Europe/Budapest", lat: 47.5, lon: 19.04, rank: 2, region: "Europe" },
  { id: "bratislava", name: "Bratislava", country: "Slovakia", tz: "Europe/Bratislava", lat: 48.15, lon: 17.11, rank: 3, region: "Europe" },
  { id: "ljubljana", name: "Ljubljana", country: "Slovenia", tz: "Europe/Ljubljana", lat: 46.05, lon: 14.51, rank: 3, region: "Europe" },
  { id: "zagreb", name: "Zagreb", country: "Croatia", tz: "Europe/Zagreb", lat: 45.81, lon: 15.98, rank: 3, region: "Europe" },
  { id: "sarajevo", name: "Sarajevo", country: "Bosnia and Herzegovina", tz: "Europe/Sarajevo", lat: 43.86, lon: 18.41, rank: 3, region: "Europe" },
  { id: "belgrade", name: "Belgrade", country: "Serbia", tz: "Europe/Belgrade", lat: 44.82, lon: 20.46, rank: 3, region: "Europe" },
  { id: "podgorica", name: "Podgorica", country: "Montenegro", tz: "Europe/Podgorica", lat: 42.43, lon: 19.26, rank: 4, region: "Europe" },
  { id: "pristina", name: "Pristina", country: "Kosovo", tz: "Europe/Belgrade", lat: 42.66, lon: 21.16, rank: 4, region: "Europe" },
  { id: "skopje", name: "Skopje", country: "North Macedonia", tz: "Europe/Skopje", lat: 41.99, lon: 21.43, rank: 4, region: "Europe" },
  { id: "tirana", name: "Tirana", country: "Albania", tz: "Europe/Tirane", lat: 41.33, lon: 19.82, rank: 3, region: "Europe" },
  { id: "sofia", name: "Sofia", country: "Bulgaria", tz: "Europe/Sofia", lat: 42.7, lon: 23.32, rank: 3, region: "Europe" },
  { id: "bucharest", name: "Bucharest", country: "Romania", tz: "Europe/Bucharest", lat: 44.43, lon: 26.1, rank: 2, region: "Europe" },
  { id: "chisinau", name: "Chișinău", country: "Moldova", tz: "Europe/Chisinau", lat: 47.01, lon: 28.86, rank: 3, region: "Europe" },
  { id: "kyiv", name: "Kyiv", country: "Ukraine", tz: "Europe/Kyiv", lat: 50.45, lon: 30.52, rank: 2, region: "Europe" },
  { id: "minsk", name: "Minsk", country: "Belarus", tz: "Europe/Minsk", lat: 53.9, lon: 27.57, rank: 3, region: "Europe" },
  { id: "vilnius", name: "Vilnius", country: "Lithuania", tz: "Europe/Vilnius", lat: 54.69, lon: 25.28, rank: 3, region: "Europe" },
  { id: "riga", name: "Riga", country: "Latvia", tz: "Europe/Riga", lat: 56.95, lon: 24.11, rank: 3, region: "Europe" },
  { id: "tallinn", name: "Tallinn", country: "Estonia", tz: "Europe/Tallinn", lat: 59.44, lon: 24.75, rank: 3, region: "Europe" },
  { id: "valletta", name: "Valletta", country: "Malta", tz: "Europe/Malta", lat: 35.9, lon: 14.51, rank: 4, region: "Europe" },
  { id: "nicosia", name: "Nicosia", country: "Cyprus", tz: "Asia/Nicosia", lat: 35.19, lon: 33.38, rank: 3, region: "Europe" },
  { id: "monaco", name: "Monaco", country: "Monaco", tz: "Europe/Monaco", lat: 43.74, lon: 7.42, rank: 5, region: "Europe" },
  { id: "andorra_la_vella", name: "Andorra la Vella", country: "Andorra", tz: "Europe/Andorra", lat: 42.51, lon: 1.52, rank: 5, region: "Europe" },
  { id: "san_marino", name: "San Marino", country: "San Marino", tz: "Europe/San_Marino", lat: 43.94, lon: 12.45, rank: 5, region: "Europe" },
  { id: "vatican", name: "Vatican City", country: "Vatican City", tz: "Europe/Rome", lat: 41.9, lon: 12.45, rank: 5, region: "Europe" },
  { id: "vaduz", name: "Vaduz", country: "Liechtenstein", tz: "Europe/Vaduz", lat: 47.14, lon: 9.52, rank: 5, region: "Europe" },
  { id: "tbilisi", name: "Tbilisi", country: "Georgia", tz: "Asia/Tbilisi", lat: 41.72, lon: 44.78, rank: 3, region: "Europe" },
  { id: "yerevan", name: "Yerevan", country: "Armenia", tz: "Asia/Yerevan", lat: 40.18, lon: 44.51, rank: 3, region: "Europe" },
  { id: "baku", name: "Baku", country: "Azerbaijan", tz: "Asia/Baku", lat: 40.41, lon: 49.87, rank: 3, region: "Europe" },

  // Africa
  { id: "rabat", name: "Rabat", country: "Morocco", tz: "Africa/Casablanca", lat: 34.02, lon: -6.84, rank: 3, region: "Africa" },
  { id: "algiers", name: "Algiers", country: "Algeria", tz: "Africa/Algiers", lat: 36.75, lon: 3.06, rank: 2, region: "Africa" },
  { id: "tunis", name: "Tunis", country: "Tunisia", tz: "Africa/Tunis", lat: 36.81, lon: 10.18, rank: 3, region: "Africa" },
  { id: "tripoli", name: "Tripoli", country: "Libya", tz: "Africa/Tripoli", lat: 32.89, lon: 13.19, rank: 3, region: "Africa" },
  { id: "khartoum", name: "Khartoum", country: "Sudan", tz: "Africa/Khartoum", lat: 15.5, lon: 32.56, rank: 3, region: "Africa" },
  { id: "juba", name: "Juba", country: "South Sudan", tz: "Africa/Juba", lat: 4.86, lon: 31.57, rank: 4, region: "Africa" },
  { id: "addis_ababa", name: "Addis Ababa", country: "Ethiopia", tz: "Africa/Addis_Ababa", lat: 9.03, lon: 38.74, rank: 2, region: "Africa" },
  { id: "asmara", name: "Asmara", country: "Eritrea", tz: "Africa/Asmara", lat: 15.34, lon: 38.93, rank: 4, region: "Africa" },
  { id: "djibouti", name: "Djibouti", country: "Djibouti", tz: "Africa/Djibouti", lat: 11.59, lon: 43.15, rank: 4, region: "Africa" },
  { id: "mogadishu", name: "Mogadishu", country: "Somalia", tz: "Africa/Mogadishu", lat: 2.05, lon: 45.32, rank: 3, region: "Africa" },
  { id: "kampala", name: "Kampala", country: "Uganda", tz: "Africa/Kampala", lat: 0.35, lon: 32.58, rank: 3, region: "Africa" },
  { id: "kigali", name: "Kigali", country: "Rwanda", tz: "Africa/Kigali", lat: -1.94, lon: 30.06, rank: 3, region: "Africa" },
  { id: "bujumbura", name: "Gitega", country: "Burundi", tz: "Africa/Bujumbura", lat: -3.43, lon: 29.93, rank: 4, region: "Africa" },
  { id: "dodoma", name: "Dodoma", country: "Tanzania", tz: "Africa/Dar_es_Salaam", lat: -6.16, lon: 35.75, rank: 3, region: "Africa" },
  { id: "lilongwe", name: "Lilongwe", country: "Malawi", tz: "Africa/Blantyre", lat: -13.98, lon: 33.77, rank: 4, region: "Africa" },
  { id: "lusaka", name: "Lusaka", country: "Zambia", tz: "Africa/Lusaka", lat: -15.42, lon: 28.28, rank: 3, region: "Africa" },
  { id: "harare", name: "Harare", country: "Zimbabwe", tz: "Africa/Harare", lat: -17.83, lon: 31.05, rank: 3, region: "Africa" },
  { id: "maputo", name: "Maputo", country: "Mozambique", tz: "Africa/Maputo", lat: -25.97, lon: 32.57, rank: 3, region: "Africa" },
  { id: "antananarivo", name: "Antananarivo", country: "Madagascar", tz: "Indian/Antananarivo", lat: -18.88, lon: 47.51, rank: 3, region: "Africa" },
  { id: "port_louis", name: "Port Louis", country: "Mauritius", tz: "Indian/Mauritius", lat: -20.16, lon: 57.5, rank: 4, region: "Africa" },
  { id: "victoria_sc", name: "Victoria", country: "Seychelles", tz: "Indian/Mahe", lat: -4.62, lon: 55.45, rank: 5, region: "Africa" },
  { id: "moroni", name: "Moroni", country: "Comoros", tz: "Indian/Comoro", lat: -11.7, lon: 43.26, rank: 5, region: "Africa" },
  { id: "pretoria", name: "Pretoria", country: "South Africa", tz: "Africa/Johannesburg", lat: -25.75, lon: 28.19, rank: 3, region: "Africa" },
  { id: "gaborone", name: "Gaborone", country: "Botswana", tz: "Africa/Gaborone", lat: -24.65, lon: 25.91, rank: 4, region: "Africa" },
  { id: "windhoek", name: "Windhoek", country: "Namibia", tz: "Africa/Windhoek", lat: -22.56, lon: 17.08, rank: 3, region: "Africa" },
  { id: "maseru", name: "Maseru", country: "Lesotho", tz: "Africa/Maseru", lat: -29.31, lon: 27.48, rank: 4, region: "Africa" },
  { id: "mbabane", name: "Mbabane", country: "Eswatini", tz: "Africa/Mbabane", lat: -26.32, lon: 31.14, rank: 4, region: "Africa" },
  { id: "luanda", name: "Luanda", country: "Angola", tz: "Africa/Luanda", lat: -8.84, lon: 13.23, rank: 2, region: "Africa" },
  { id: "kinshasa", name: "Kinshasa", country: "DR Congo", tz: "Africa/Kinshasa", lat: -4.32, lon: 15.31, rank: 2, region: "Africa" },
  { id: "brazzaville", name: "Brazzaville", country: "Congo", tz: "Africa/Brazzaville", lat: -4.27, lon: 15.28, rank: 3, region: "Africa" },
  { id: "libreville", name: "Libreville", country: "Gabon", tz: "Africa/Libreville", lat: 0.39, lon: 9.45, rank: 3, region: "Africa" },
  { id: "malabo", name: "Malabo", country: "Equatorial Guinea", tz: "Africa/Malabo", lat: 3.75, lon: 8.78, rank: 4, region: "Africa" },
  { id: "yaounde", name: "Yaoundé", country: "Cameroon", tz: "Africa/Douala", lat: 3.87, lon: 11.52, rank: 3, region: "Africa" },
  { id: "bangui", name: "Bangui", country: "Central African Republic", tz: "Africa/Bangui", lat: 4.39, lon: 18.56, rank: 4, region: "Africa" },
  { id: "ndjamena", name: "N'Djamena", country: "Chad", tz: "Africa/Ndjamena", lat: 12.13, lon: 15.05, rank: 3, region: "Africa" },
  { id: "niamey", name: "Niamey", country: "Niger", tz: "Africa/Niamey", lat: 13.51, lon: 2.11, rank: 3, region: "Africa" },
  { id: "abuja", name: "Abuja", country: "Nigeria", tz: "Africa/Lagos", lat: 9.08, lon: 7.4, rank: 3, region: "Africa" },
  { id: "porto_novo", name: "Porto-Novo", country: "Benin", tz: "Africa/Porto-Novo", lat: 6.5, lon: 2.6, rank: 4, region: "Africa" },
  { id: "lome", name: "Lomé", country: "Togo", tz: "Africa/Lome", lat: 6.13, lon: 1.22, rank: 4, region: "Africa" },
  { id: "accra", name: "Accra", country: "Ghana", tz: "Africa/Accra", lat: 5.56, lon: -0.21, rank: 2, region: "Africa" },
  { id: "ouagadougou", name: "Ouagadougou", country: "Burkina Faso", tz: "Africa/Ouagadougou", lat: 12.37, lon: -1.53, rank: 3, region: "Africa" },
  { id: "bamako", name: "Bamako", country: "Mali", tz: "Africa/Bamako", lat: 12.65, lon: -8.0, rank: 3, region: "Africa" },
  { id: "dakar", name: "Dakar", country: "Senegal", tz: "Africa/Dakar", lat: 14.69, lon: -17.45, rank: 2, region: "Africa" },
  { id: "banjul", name: "Banjul", country: "Gambia", tz: "Africa/Banjul", lat: 13.45, lon: -16.58, rank: 4, region: "Africa" },
  { id: "bissau", name: "Bissau", country: "Guinea-Bissau", tz: "Africa/Bissau", lat: 11.86, lon: -15.6, rank: 4, region: "Africa" },
  { id: "conakry", name: "Conakry", country: "Guinea", tz: "Africa/Conakry", lat: 9.51, lon: -13.71, rank: 3, region: "Africa" },
  { id: "freetown", name: "Freetown", country: "Sierra Leone", tz: "Africa/Freetown", lat: 8.48, lon: -13.23, rank: 4, region: "Africa" },
  { id: "monrovia", name: "Monrovia", country: "Liberia", tz: "Africa/Monrovia", lat: 6.3, lon: -10.8, rank: 4, region: "Africa" },
  { id: "abidjan", name: "Abidjan", country: "Côte d'Ivoire", tz: "Africa/Abidjan", lat: 5.36, lon: -4.01, rank: 2, region: "Africa" },
  { id: "nouakchott", name: "Nouakchott", country: "Mauritania", tz: "Africa/Nouakchott", lat: 18.08, lon: -15.98, rank: 3, region: "Africa" },
  { id: "praia", name: "Praia", country: "Cabo Verde", tz: "Atlantic/Cape_Verde", lat: 14.92, lon: -23.51, rank: 4, region: "Africa" },
  { id: "sao_tome", name: "São Tomé", country: "São Tomé and Príncipe", tz: "Africa/Sao_Tome", lat: 0.34, lon: 6.73, rank: 5, region: "Africa" },

  // Asia & Middle East
  { id: "riyadh", name: "Riyadh", country: "Saudi Arabia", tz: "Asia/Riyadh", lat: 24.71, lon: 46.68, rank: 2, region: "Asia" },
  { id: "kuwait_city", name: "Kuwait City", country: "Kuwait", tz: "Asia/Kuwait", lat: 29.38, lon: 47.99, rank: 3, region: "Asia" },
  { id: "doha", name: "Doha", country: "Qatar", tz: "Asia/Qatar", lat: 25.29, lon: 51.53, rank: 2, region: "Asia" },
  { id: "manama", name: "Manama", country: "Bahrain", tz: "Asia/Bahrain", lat: 26.23, lon: 50.59, rank: 4, region: "Asia" },
  { id: "muscat", name: "Muscat", country: "Oman", tz: "Asia/Muscat", lat: 23.59, lon: 58.41, rank: 3, region: "Asia" },
  { id: "sanaa", name: "Sana'a", country: "Yemen", tz: "Asia/Aden", lat: 15.37, lon: 44.19, rank: 3, region: "Asia" },
  { id: "baghdad", name: "Baghdad", country: "Iraq", tz: "Asia/Baghdad", lat: 33.32, lon: 44.37, rank: 2, region: "Asia" },
  { id: "jerusalem", name: "Jerusalem", country: "Israel", tz: "Asia/Jerusalem", lat: 31.77, lon: 35.22, rank: 2, region: "Asia" },
  { id: "amman", name: "Amman", country: "Jordan", tz: "Asia/Amman", lat: 31.95, lon: 35.93, rank: 3, region: "Asia" },
  { id: "beirut", name: "Beirut", country: "Lebanon", tz: "Asia/Beirut", lat: 33.89, lon: 35.5, rank: 3, region: "Asia" },
  { id: "damascus", name: "Damascus", country: "Syria", tz: "Asia/Damascus", lat: 33.51, lon: 36.29, rank: 3, region: "Asia" },
  { id: "ramallah", name: "Ramallah", country: "Palestine", tz: "Asia/Hebron", lat: 31.9, lon: 35.2, rank: 4, region: "Asia" },
  { id: "kabul", name: "Kabul", country: "Afghanistan", tz: "Asia/Kabul", lat: 34.53, lon: 69.17, rank: 3, region: "Asia" },
  { id: "islamabad", name: "Islamabad", country: "Pakistan", tz: "Asia/Karachi", lat: 33.68, lon: 73.05, rank: 3, region: "Asia" },
  { id: "kathmandu", name: "Kathmandu", country: "Nepal", tz: "Asia/Kathmandu", lat: 27.72, lon: 85.32, rank: 3, region: "Asia" },
  { id: "thimphu", name: "Thimphu", country: "Bhutan", tz: "Asia/Thimphu", lat: 27.47, lon: 89.64, rank: 4, region: "Asia" },
  { id: "colombo", name: "Colombo", country: "Sri Lanka", tz: "Asia/Colombo", lat: 6.93, lon: 79.86, rank: 3, region: "Asia" },
  { id: "male", name: "Malé", country: "Maldives", tz: "Indian/Maldives", lat: 4.18, lon: 73.51, rank: 4, region: "Asia" },
  { id: "tashkent", name: "Tashkent", country: "Uzbekistan", tz: "Asia/Tashkent", lat: 41.3, lon: 69.24, rank: 3, region: "Asia" },
  { id: "astana", name: "Astana", country: "Kazakhstan", tz: "Asia/Almaty", lat: 51.17, lon: 71.45, rank: 3, region: "Asia" },
  { id: "almaty", name: "Almaty", country: "Kazakhstan", tz: "Asia/Almaty", lat: 43.24, lon: 76.95, rank: 3, region: "Asia" },
  { id: "bishkek", name: "Bishkek", country: "Kyrgyzstan", tz: "Asia/Bishkek", lat: 42.87, lon: 74.59, rank: 4, region: "Asia" },
  { id: "dushanbe", name: "Dushanbe", country: "Tajikistan", tz: "Asia/Dushanbe", lat: 38.56, lon: 68.77, rank: 4, region: "Asia" },
  { id: "ashgabat", name: "Ashgabat", country: "Turkmenistan", tz: "Asia/Ashgabat", lat: 37.96, lon: 58.38, rank: 4, region: "Asia" },
  { id: "ulaanbaatar", name: "Ulaanbaatar", country: "Mongolia", tz: "Asia/Ulaanbaatar", lat: 47.92, lon: 106.92, rank: 3, region: "Asia" },
  { id: "pyongyang", name: "Pyongyang", country: "North Korea", tz: "Asia/Pyongyang", lat: 39.04, lon: 125.75, rank: 3, region: "Asia" },
  { id: "hanoi", name: "Hanoi", country: "Vietnam", tz: "Asia/Ho_Chi_Minh", lat: 21.03, lon: 105.85, rank: 2, region: "Asia" },
  { id: "ho_chi_minh", name: "Ho Chi Minh City", country: "Vietnam", tz: "Asia/Ho_Chi_Minh", lat: 10.82, lon: 106.63, rank: 2, region: "Asia" },
  { id: "phnom_penh", name: "Phnom Penh", country: "Cambodia", tz: "Asia/Phnom_Penh", lat: 11.56, lon: 104.93, rank: 3, region: "Asia" },
  { id: "vientiane", name: "Vientiane", country: "Laos", tz: "Asia/Vientiane", lat: 17.98, lon: 102.63, rank: 4, region: "Asia" },
  { id: "naypyidaw", name: "Naypyidaw", country: "Myanmar", tz: "Asia/Yangon", lat: 19.76, lon: 96.08, rank: 3, region: "Asia" },
  { id: "yangon", name: "Yangon", country: "Myanmar", tz: "Asia/Yangon", lat: 16.87, lon: 96.2, rank: 3, region: "Asia" },
  { id: "kuala_lumpur", name: "Kuala Lumpur", country: "Malaysia", tz: "Asia/Kuala_Lumpur", lat: 3.14, lon: 101.69, rank: 2, region: "Asia" },
  { id: "manila", name: "Manila", country: "Philippines", tz: "Asia/Manila", lat: 14.6, lon: 120.98, rank: 2, region: "Asia" },
  { id: "bandar_seri_begawan", name: "Bandar Seri Begawan", country: "Brunei", tz: "Asia/Brunei", lat: 4.9, lon: 114.94, rank: 4, region: "Asia" },
  { id: "dili", name: "Dili", country: "Timor-Leste", tz: "Asia/Dili", lat: -8.56, lon: 125.57, rank: 4, region: "Asia" },

  // Oceania
  { id: "wellington", name: "Wellington", country: "New Zealand", tz: "Pacific/Auckland", lat: -41.29, lon: 174.78, rank: 3, region: "Oceania" },
  { id: "canberra", name: "Canberra", country: "Australia", tz: "Australia/Sydney", lat: -35.28, lon: 149.13, rank: 3, region: "Oceania" },
  { id: "port_moresby", name: "Port Moresby", country: "Papua New Guinea", tz: "Pacific/Port_Moresby", lat: -9.44, lon: 147.18, rank: 3, region: "Oceania" },
  { id: "suva", name: "Suva", country: "Fiji", tz: "Pacific/Fiji", lat: -18.14, lon: 178.44, rank: 3, region: "Oceania" },
  { id: "nuku_alofa", name: "Nukuʻalofa", country: "Tonga", tz: "Pacific/Tongatapu", lat: -21.13, lon: -175.2, rank: 4, region: "Oceania" },
  { id: "apia", name: "Apia", country: "Samoa", tz: "Pacific/Apia", lat: -13.83, lon: -171.77, rank: 4, region: "Oceania" },
  { id: "noumea", name: "Nouméa", country: "New Caledonia", tz: "Pacific/Noumea", lat: -22.28, lon: 166.46, rank: 4, region: "Oceania" },
  { id: "port_vila", name: "Port Vila", country: "Vanuatu", tz: "Pacific/Efate", lat: -17.73, lon: 168.32, rank: 4, region: "Oceania" },
  { id: "honiara", name: "Honiara", country: "Solomon Islands", tz: "Pacific/Guadalcanal", lat: -9.43, lon: 159.95, rank: 4, region: "Oceania" },
  { id: "tarawa", name: "Tarawa", country: "Kiribati", tz: "Pacific/Tarawa", lat: 1.45, lon: 173.0, rank: 4, region: "Oceania" },
  { id: "funafuti", name: "Funafuti", country: "Tuvalu", tz: "Pacific/Funafuti", lat: -8.52, lon: 179.2, rank: 5, region: "Oceania" },
  { id: "palikir", name: "Palikir", country: "Micronesia", tz: "Pacific/Pohnpei", lat: 6.92, lon: 158.16, rank: 5, region: "Oceania" },
  { id: "majuro", name: "Majuro", country: "Marshall Islands", tz: "Pacific/Majuro", lat: 7.09, lon: 171.38, rank: 5, region: "Oceania" },
  { id: "ngerulmud", name: "Ngerulmud", country: "Palau", tz: "Pacific/Palau", lat: 7.5, lon: 134.62, rank: 5, region: "Oceania" },
  { id: "yaren", name: "Yaren", country: "Nauru", tz: "Pacific/Nauru", lat: -0.55, lon: 166.92, rank: 5, region: "Oceania" },
];
