/**
 * Extra major cities beyond the capital / watch-list set.
 * Shown on country hover and available in the city search picker.
 * These are never treated as capitals.
 */

export const EXTRA_CITIES = [
  // ---------- Americas ----------
  // USA (beyond watch list)
  { id: "san_francisco", name: "San Francisco", country: "USA", tz: "America/Los_Angeles", lat: 37.77, lon: -122.42, rank: 2, region: "Americas" },
  { id: "seattle", name: "Seattle", country: "USA", tz: "America/Los_Angeles", lat: 47.61, lon: -122.33, rank: 2, region: "Americas" },
  { id: "miami", name: "Miami", country: "USA", tz: "America/New_York", lat: 25.76, lon: -80.19, rank: 2, region: "Americas" },
  { id: "boston", name: "Boston", country: "USA", tz: "America/New_York", lat: 42.36, lon: -71.06, rank: 2, region: "Americas" },
  { id: "dallas", name: "Dallas", country: "USA", tz: "America/Chicago", lat: 32.78, lon: -96.8, rank: 2, region: "Americas" },
  { id: "houston", name: "Houston", country: "USA", tz: "America/Chicago", lat: 29.76, lon: -95.37, rank: 2, region: "Americas" },
  { id: "atlanta", name: "Atlanta", country: "USA", tz: "America/New_York", lat: 33.75, lon: -84.39, rank: 2, region: "Americas" },
  { id: "phoenix", name: "Phoenix", country: "USA", tz: "America/Phoenix", lat: 33.45, lon: -112.07, rank: 3, region: "Americas" },
  { id: "philadelphia", name: "Philadelphia", country: "USA", tz: "America/New_York", lat: 39.95, lon: -75.17, rank: 2, region: "Americas" },
  { id: "las_vegas", name: "Las Vegas", country: "USA", tz: "America/Los_Angeles", lat: 36.17, lon: -115.14, rank: 3, region: "Americas" },
  { id: "detroit", name: "Detroit", country: "USA", tz: "America/Detroit", lat: 42.33, lon: -83.05, rank: 3, region: "Americas" },
  { id: "minneapolis", name: "Minneapolis", country: "USA", tz: "America/Chicago", lat: 44.98, lon: -93.27, rank: 3, region: "Americas" },

  // Canada
  { id: "montreal", name: "Montreal", country: "Canada", tz: "America/Toronto", lat: 45.5, lon: -73.57, rank: 2, region: "Americas" },
  { id: "calgary", name: "Calgary", country: "Canada", tz: "America/Edmonton", lat: 51.05, lon: -114.07, rank: 2, region: "Americas" },
  { id: "edmonton", name: "Edmonton", country: "Canada", tz: "America/Edmonton", lat: 53.55, lon: -113.49, rank: 3, region: "Americas" },
  { id: "winnipeg", name: "Winnipeg", country: "Canada", tz: "America/Winnipeg", lat: 49.9, lon: -97.14, rank: 3, region: "Americas" },
  { id: "quebec_city", name: "Quebec City", country: "Canada", tz: "America/Toronto", lat: 46.81, lon: -71.21, rank: 3, region: "Americas" },
  { id: "halifax", name: "Halifax", country: "Canada", tz: "America/Halifax", lat: 44.65, lon: -63.57, rank: 3, region: "Americas" },

  // Mexico
  { id: "guadalajara", name: "Guadalajara", country: "Mexico", tz: "America/Mexico_City", lat: 20.67, lon: -103.35, rank: 2, region: "Americas" },
  { id: "monterrey", name: "Monterrey", country: "Mexico", tz: "America/Monterrey", lat: 25.67, lon: -100.31, rank: 2, region: "Americas" },
  { id: "cancun", name: "Cancún", country: "Mexico", tz: "America/Cancun", lat: 21.16, lon: -86.85, rank: 3, region: "Americas" },
  { id: "tijuana", name: "Tijuana", country: "Mexico", tz: "America/Tijuana", lat: 32.51, lon: -117.04, rank: 3, region: "Americas" },
  { id: "puebla", name: "Puebla", country: "Mexico", tz: "America/Mexico_City", lat: 19.04, lon: -98.2, rank: 3, region: "Americas" },
  { id: "merida_mx", name: "Mérida", country: "Mexico", tz: "America/Merida", lat: 20.97, lon: -89.62, rank: 4, region: "Americas" },

  // Central America & Caribbean
  { id: "antigua_gt", name: "Antigua", country: "Guatemala", tz: "America/Guatemala", lat: 14.56, lon: -90.73, rank: 4, region: "Americas" },
  { id: "quetzaltenango", name: "Quetzaltenango", country: "Guatemala", tz: "America/Guatemala", lat: 14.83, lon: -91.52, rank: 4, region: "Americas" },
  { id: "san_pedro_sula", name: "San Pedro Sula", country: "Honduras", tz: "America/Tegucigalpa", lat: 15.5, lon: -88.03, rank: 4, region: "Americas" },
  { id: "leon_ni", name: "León", country: "Nicaragua", tz: "America/Managua", lat: 12.44, lon: -86.88, rank: 4, region: "Americas" },
  { id: "limon_cr", name: "Limón", country: "Costa Rica", tz: "America/Costa_Rica", lat: 9.99, lon: -83.04, rank: 4, region: "Americas" },
  { id: "colon_pa", name: "Colón", country: "Panama", tz: "America/Panama", lat: 9.36, lon: -79.9, rank: 4, region: "Americas" },
  { id: "santiago_cuba", name: "Santiago de Cuba", country: "Cuba", tz: "America/Havana", lat: 20.02, lon: -75.83, rank: 3, region: "Americas" },
  { id: "montego_bay", name: "Montego Bay", country: "Jamaica", tz: "America/Jamaica", lat: 18.47, lon: -77.92, rank: 4, region: "Americas" },
  { id: "cap_haitien", name: "Cap-Haïtien", country: "Haiti", tz: "America/Port-au-Prince", lat: 19.76, lon: -72.2, rank: 4, region: "Americas" },
  { id: "santiago_dr", name: "Santiago", country: "Dominican Republic", tz: "America/Santo_Domingo", lat: 19.45, lon: -70.69, rank: 4, region: "Americas" },
  { id: "ponce", name: "Ponce", country: "Puerto Rico", tz: "America/Puerto_Rico", lat: 18.01, lon: -66.61, rank: 5, region: "Americas" },
  { id: "freeport_bs", name: "Freeport", country: "Bahamas", tz: "America/Nassau", lat: 26.53, lon: -78.7, rank: 5, region: "Americas" },
  { id: "san_fernando_tt", name: "San Fernando", country: "Trinidad and Tobago", tz: "America/Port_of_Spain", lat: 10.28, lon: -61.47, rank: 5, region: "Americas" },

  // South America
  { id: "maracaibo", name: "Maracaibo", country: "Venezuela", tz: "America/Caracas", lat: 10.65, lon: -71.64, rank: 3, region: "Americas" },
  { id: "valencia_ve", name: "Valencia", country: "Venezuela", tz: "America/Caracas", lat: 10.16, lon: -68.01, rank: 3, region: "Americas" },
  { id: "guayaquil", name: "Guayaquil", country: "Ecuador", tz: "America/Guayaquil", lat: -2.17, lon: -79.92, rank: 2, region: "Americas" },
  { id: "cuenca_ec", name: "Cuenca", country: "Ecuador", tz: "America/Guayaquil", lat: -2.9, lon: -79.0, rank: 4, region: "Americas" },
  { id: "arequipa", name: "Arequipa", country: "Peru", tz: "America/Lima", lat: -16.41, lon: -71.54, rank: 3, region: "Americas" },
  { id: "cusco", name: "Cusco", country: "Peru", tz: "America/Lima", lat: -13.53, lon: -71.97, rank: 3, region: "Americas" },
  { id: "trujillo_pe", name: "Trujillo", country: "Peru", tz: "America/Lima", lat: -8.11, lon: -79.03, rank: 4, region: "Americas" },
  { id: "santa_cruz_bo", name: "Santa Cruz", country: "Bolivia", tz: "America/La_Paz", lat: -17.78, lon: -63.18, rank: 3, region: "Americas" },
  { id: "cochabamba", name: "Cochabamba", country: "Bolivia", tz: "America/La_Paz", lat: -17.39, lon: -66.16, rank: 4, region: "Americas" },
  { id: "ciudad_del_este", name: "Ciudad del Este", country: "Paraguay", tz: "America/Asuncion", lat: -25.51, lon: -54.61, rank: 4, region: "Americas" },
  { id: "punta_del_este", name: "Punta del Este", country: "Uruguay", tz: "America/Montevideo", lat: -34.97, lon: -54.95, rank: 4, region: "Americas" },
  { id: "medellin", name: "Medellín", country: "Colombia", tz: "America/Bogota", lat: 6.25, lon: -75.56, rank: 2, region: "Americas" },
  { id: "cali", name: "Cali", country: "Colombia", tz: "America/Bogota", lat: 3.45, lon: -76.53, rank: 2, region: "Americas" },
  { id: "barranquilla", name: "Barranquilla", country: "Colombia", tz: "America/Bogota", lat: 10.96, lon: -74.8, rank: 3, region: "Americas" },
  { id: "cartagena_co", name: "Cartagena", country: "Colombia", tz: "America/Bogota", lat: 10.39, lon: -75.51, rank: 3, region: "Americas" },
  { id: "valparaiso", name: "Valparaíso", country: "Chile", tz: "America/Santiago", lat: -33.05, lon: -71.62, rank: 3, region: "Americas" },
  { id: "concepcion_cl", name: "Concepción", country: "Chile", tz: "America/Santiago", lat: -36.83, lon: -73.05, rank: 3, region: "Americas" },
  { id: "antofagasta", name: "Antofagasta", country: "Chile", tz: "America/Santiago", lat: -23.65, lon: -70.4, rank: 4, region: "Americas" },
  { id: "cordoba_ar", name: "Córdoba", country: "Argentina", tz: "America/Argentina/Cordoba", lat: -31.42, lon: -64.18, rank: 2, region: "Americas" },
  { id: "rosario", name: "Rosario", country: "Argentina", tz: "America/Argentina/Buenos_Aires", lat: -32.95, lon: -60.64, rank: 2, region: "Americas" },
  { id: "mendoza", name: "Mendoza", country: "Argentina", tz: "America/Argentina/Mendoza", lat: -32.89, lon: -68.83, rank: 3, region: "Americas" },
  { id: "bariloche", name: "Bariloche", country: "Argentina", tz: "America/Argentina/Buenos_Aires", lat: -41.13, lon: -71.31, rank: 4, region: "Americas" },
  { id: "rio_de_janeiro", name: "Rio de Janeiro", country: "Brazil", tz: "America/Sao_Paulo", lat: -22.91, lon: -43.17, rank: 1, region: "Americas" },
  { id: "salvador_br", name: "Salvador", country: "Brazil", tz: "America/Bahia", lat: -12.97, lon: -38.51, rank: 2, region: "Americas" },
  { id: "belo_horizonte", name: "Belo Horizonte", country: "Brazil", tz: "America/Sao_Paulo", lat: -19.92, lon: -43.94, rank: 2, region: "Americas" },
  { id: "fortaleza", name: "Fortaleza", country: "Brazil", tz: "America/Fortaleza", lat: -3.72, lon: -38.54, rank: 2, region: "Americas" },
  { id: "manaus", name: "Manaus", country: "Brazil", tz: "America/Manaus", lat: -3.12, lon: -60.02, rank: 3, region: "Americas" },
  { id: "curitiba", name: "Curitiba", country: "Brazil", tz: "America/Sao_Paulo", lat: -25.43, lon: -49.27, rank: 2, region: "Americas" },
  { id: "recife", name: "Recife", country: "Brazil", tz: "America/Recife", lat: -8.05, lon: -34.88, rank: 2, region: "Americas" },
  { id: "porto_alegre", name: "Porto Alegre", country: "Brazil", tz: "America/Sao_Paulo", lat: -30.03, lon: -51.23, rank: 2, region: "Americas" },

  // ---------- Europe ----------
  { id: "manchester", name: "Manchester", country: "UK", tz: "Europe/London", lat: 53.48, lon: -2.24, rank: 2, region: "Europe" },
  { id: "birmingham_uk", name: "Birmingham", country: "UK", tz: "Europe/London", lat: 52.49, lon: -1.9, rank: 2, region: "Europe" },
  { id: "edinburgh", name: "Edinburgh", country: "UK", tz: "Europe/London", lat: 55.95, lon: -3.19, rank: 2, region: "Europe" },
  { id: "glasgow", name: "Glasgow", country: "UK", tz: "Europe/London", lat: 55.86, lon: -4.25, rank: 2, region: "Europe" },
  { id: "liverpool", name: "Liverpool", country: "UK", tz: "Europe/London", lat: 53.41, lon: -2.99, rank: 3, region: "Europe" },
  { id: "bristol", name: "Bristol", country: "UK", tz: "Europe/London", lat: 51.45, lon: -2.59, rank: 3, region: "Europe" },
  { id: "belfast", name: "Belfast", country: "UK", tz: "Europe/London", lat: 54.6, lon: -5.93, rank: 3, region: "Europe" },
  { id: "cork", name: "Cork", country: "Ireland", tz: "Europe/Dublin", lat: 51.9, lon: -8.47, rank: 3, region: "Europe" },
  { id: "galway", name: "Galway", country: "Ireland", tz: "Europe/Dublin", lat: 53.27, lon: -9.05, rank: 4, region: "Europe" },
  { id: "porto", name: "Porto", country: "Portugal", tz: "Europe/Lisbon", lat: 41.15, lon: -8.61, rank: 2, region: "Europe" },
  { id: "faro", name: "Faro", country: "Portugal", tz: "Europe/Lisbon", lat: 37.02, lon: -7.93, rank: 4, region: "Europe" },
  { id: "barcelona", name: "Barcelona", country: "Spain", tz: "Europe/Madrid", lat: 41.39, lon: 2.17, rank: 1, region: "Europe" },
  { id: "valencia_es", name: "Valencia", country: "Spain", tz: "Europe/Madrid", lat: 39.47, lon: -0.38, rank: 2, region: "Europe" },
  { id: "seville", name: "Seville", country: "Spain", tz: "Europe/Madrid", lat: 37.39, lon: -5.99, rank: 2, region: "Europe" },
  { id: "malaga", name: "Málaga", country: "Spain", tz: "Europe/Madrid", lat: 36.72, lon: -4.42, rank: 3, region: "Europe" },
  { id: "bilbao", name: "Bilbao", country: "Spain", tz: "Europe/Madrid", lat: 43.26, lon: -2.93, rank: 3, region: "Europe" },
  { id: "lyon", name: "Lyon", country: "France", tz: "Europe/Paris", lat: 45.76, lon: 4.84, rank: 2, region: "Europe" },
  { id: "marseille", name: "Marseille", country: "France", tz: "Europe/Paris", lat: 43.3, lon: 5.37, rank: 2, region: "Europe" },
  { id: "toulouse", name: "Toulouse", country: "France", tz: "Europe/Paris", lat: 43.6, lon: 1.44, rank: 2, region: "Europe" },
  { id: "nice", name: "Nice", country: "France", tz: "Europe/Paris", lat: 43.71, lon: 7.26, rank: 3, region: "Europe" },
  { id: "bordeaux", name: "Bordeaux", country: "France", tz: "Europe/Paris", lat: 44.84, lon: -0.58, rank: 3, region: "Europe" },
  { id: "lille", name: "Lille", country: "France", tz: "Europe/Paris", lat: 50.63, lon: 3.06, rank: 3, region: "Europe" },
  { id: "rotterdam", name: "Rotterdam", country: "Netherlands", tz: "Europe/Amsterdam", lat: 51.92, lon: 4.48, rank: 2, region: "Europe" },
  { id: "the_hague", name: "The Hague", country: "Netherlands", tz: "Europe/Amsterdam", lat: 52.07, lon: 4.3, rank: 3, region: "Europe" },
  { id: "utrecht", name: "Utrecht", country: "Netherlands", tz: "Europe/Amsterdam", lat: 52.09, lon: 5.12, rank: 3, region: "Europe" },
  { id: "munich", name: "Munich", country: "Germany", tz: "Europe/Berlin", lat: 48.14, lon: 11.58, rank: 1, region: "Europe" },
  { id: "hamburg", name: "Hamburg", country: "Germany", tz: "Europe/Berlin", lat: 53.55, lon: 9.99, rank: 2, region: "Europe" },
  { id: "frankfurt", name: "Frankfurt", country: "Germany", tz: "Europe/Berlin", lat: 50.11, lon: 8.68, rank: 2, region: "Europe" },
  { id: "cologne", name: "Cologne", country: "Germany", tz: "Europe/Berlin", lat: 50.94, lon: 6.96, rank: 2, region: "Europe" },
  { id: "stuttgart", name: "Stuttgart", country: "Germany", tz: "Europe/Berlin", lat: 48.78, lon: 9.18, rank: 2, region: "Europe" },
  { id: "dusseldorf", name: "Düsseldorf", country: "Germany", tz: "Europe/Berlin", lat: 51.23, lon: 6.78, rank: 3, region: "Europe" },
  { id: "milan", name: "Milan", country: "Italy", tz: "Europe/Rome", lat: 45.46, lon: 9.19, rank: 1, region: "Europe" },
  { id: "naples", name: "Naples", country: "Italy", tz: "Europe/Rome", lat: 40.85, lon: 14.27, rank: 2, region: "Europe" },
  { id: "turin", name: "Turin", country: "Italy", tz: "Europe/Rome", lat: 45.07, lon: 7.69, rank: 2, region: "Europe" },
  { id: "florence", name: "Florence", country: "Italy", tz: "Europe/Rome", lat: 43.77, lon: 11.25, rank: 2, region: "Europe" },
  { id: "venice", name: "Venice", country: "Italy", tz: "Europe/Rome", lat: 45.44, lon: 12.32, rank: 2, region: "Europe" },
  { id: "bologna", name: "Bologna", country: "Italy", tz: "Europe/Rome", lat: 44.49, lon: 11.34, rank: 3, region: "Europe" },
  { id: "gothenburg", name: "Gothenburg", country: "Sweden", tz: "Europe/Stockholm", lat: 57.71, lon: 11.97, rank: 2, region: "Europe" },
  { id: "malmo", name: "Malmö", country: "Sweden", tz: "Europe/Stockholm", lat: 55.61, lon: 13.0, rank: 3, region: "Europe" },
  { id: "krakow", name: "Kraków", country: "Poland", tz: "Europe/Warsaw", lat: 50.06, lon: 19.94, rank: 2, region: "Europe" },
  { id: "gdansk", name: "Gdańsk", country: "Poland", tz: "Europe/Warsaw", lat: 54.35, lon: 18.65, rank: 3, region: "Europe" },
  { id: "wroclaw", name: "Wrocław", country: "Poland", tz: "Europe/Warsaw", lat: 51.11, lon: 17.04, rank: 3, region: "Europe" },
  { id: "thessaloniki", name: "Thessaloniki", country: "Greece", tz: "Europe/Athens", lat: 40.64, lon: 22.94, rank: 2, region: "Europe" },
  { id: "heraklion", name: "Heraklion", country: "Greece", tz: "Europe/Athens", lat: 35.34, lon: 25.13, rank: 4, region: "Europe" },
  { id: "tampere", name: "Tampere", country: "Finland", tz: "Europe/Helsinki", lat: 61.5, lon: 23.79, rank: 3, region: "Europe" },
  { id: "turku", name: "Turku", country: "Finland", tz: "Europe/Helsinki", lat: 60.45, lon: 22.27, rank: 3, region: "Europe" },
  { id: "ankara", name: "Ankara", country: "Türkiye", tz: "Europe/Istanbul", lat: 39.93, lon: 32.85, rank: 2, region: "Europe" },
  { id: "izmir", name: "İzmir", country: "Türkiye", tz: "Europe/Istanbul", lat: 38.42, lon: 27.14, rank: 2, region: "Europe" },
  { id: "antalya", name: "Antalya", country: "Türkiye", tz: "Europe/Istanbul", lat: 36.9, lon: 30.7, rank: 3, region: "Europe" },
  { id: "bursa", name: "Bursa", country: "Türkiye", tz: "Europe/Istanbul", lat: 40.19, lon: 29.06, rank: 3, region: "Europe" },
  { id: "saint_petersburg", name: "Saint Petersburg", country: "Russia", tz: "Europe/Moscow", lat: 59.93, lon: 30.34, rank: 1, region: "Europe" },
  { id: "novosibirsk", name: "Novosibirsk", country: "Russia", tz: "Asia/Novosibirsk", lat: 55.03, lon: 82.92, rank: 2, region: "Europe" },
  { id: "yekaterinburg", name: "Yekaterinburg", country: "Russia", tz: "Asia/Yekaterinburg", lat: 56.84, lon: 60.6, rank: 2, region: "Europe" },
  { id: "kazan", name: "Kazan", country: "Russia", tz: "Europe/Moscow", lat: 55.8, lon: 49.11, rank: 3, region: "Europe" },
  { id: "vladivostok", name: "Vladivostok", country: "Russia", tz: "Asia/Vladivostok", lat: 43.12, lon: 131.89, rank: 3, region: "Europe" },
  { id: "bergen", name: "Bergen", country: "Norway", tz: "Europe/Oslo", lat: 60.39, lon: 5.32, rank: 3, region: "Europe" },
  { id: "trondheim", name: "Trondheim", country: "Norway", tz: "Europe/Oslo", lat: 63.43, lon: 10.4, rank: 3, region: "Europe" },
  { id: "aarhus", name: "Aarhus", country: "Denmark", tz: "Europe/Copenhagen", lat: 56.16, lon: 10.21, rank: 3, region: "Europe" },
  { id: "antwerp", name: "Antwerp", country: "Belgium", tz: "Europe/Brussels", lat: 51.22, lon: 4.4, rank: 2, region: "Europe" },
  { id: "ghent", name: "Ghent", country: "Belgium", tz: "Europe/Brussels", lat: 51.05, lon: 3.73, rank: 3, region: "Europe" },
  { id: "geneva", name: "Geneva", country: "Switzerland", tz: "Europe/Zurich", lat: 46.2, lon: 6.14, rank: 2, region: "Europe" },
  { id: "basel", name: "Basel", country: "Switzerland", tz: "Europe/Zurich", lat: 47.56, lon: 7.59, rank: 3, region: "Europe" },
  { id: "lausanne", name: "Lausanne", country: "Switzerland", tz: "Europe/Zurich", lat: 46.52, lon: 6.63, rank: 3, region: "Europe" },
  { id: "salzburg", name: "Salzburg", country: "Austria", tz: "Europe/Vienna", lat: 47.81, lon: 13.04, rank: 3, region: "Europe" },
  { id: "innsbruck", name: "Innsbruck", country: "Austria", tz: "Europe/Vienna", lat: 47.27, lon: 11.39, rank: 3, region: "Europe" },
  { id: "graz", name: "Graz", country: "Austria", tz: "Europe/Vienna", lat: 47.07, lon: 15.44, rank: 3, region: "Europe" },
  { id: "brno", name: "Brno", country: "Czechia", tz: "Europe/Prague", lat: 49.2, lon: 16.61, rank: 3, region: "Europe" },
  { id: "ostrava", name: "Ostrava", country: "Czechia", tz: "Europe/Prague", lat: 49.82, lon: 18.26, rank: 4, region: "Europe" },
  { id: "debrecen", name: "Debrecen", country: "Hungary", tz: "Europe/Budapest", lat: 47.53, lon: 21.63, rank: 3, region: "Europe" },
  { id: "kosice", name: "Košice", country: "Slovakia", tz: "Europe/Bratislava", lat: 48.72, lon: 21.26, rank: 4, region: "Europe" },
  { id: "split", name: "Split", country: "Croatia", tz: "Europe/Zagreb", lat: 43.51, lon: 16.44, rank: 3, region: "Europe" },
  { id: "dubrovnik", name: "Dubrovnik", country: "Croatia", tz: "Europe/Zagreb", lat: 42.65, lon: 18.09, rank: 4, region: "Europe" },
  { id: "novi_sad", name: "Novi Sad", country: "Serbia", tz: "Europe/Belgrade", lat: 45.25, lon: 19.84, rank: 3, region: "Europe" },
  { id: "plovdiv", name: "Plovdiv", country: "Bulgaria", tz: "Europe/Sofia", lat: 42.14, lon: 24.75, rank: 3, region: "Europe" },
  { id: "varna", name: "Varna", country: "Bulgaria", tz: "Europe/Sofia", lat: 43.21, lon: 27.91, rank: 3, region: "Europe" },
  { id: "cluj", name: "Cluj-Napoca", country: "Romania", tz: "Europe/Bucharest", lat: 46.77, lon: 23.59, rank: 3, region: "Europe" },
  { id: "timisoara", name: "Timișoara", country: "Romania", tz: "Europe/Bucharest", lat: 45.75, lon: 21.23, rank: 3, region: "Europe" },
  { id: "iasi", name: "Iași", country: "Romania", tz: "Europe/Bucharest", lat: 47.16, lon: 27.59, rank: 3, region: "Europe" },
  { id: "lviv", name: "Lviv", country: "Ukraine", tz: "Europe/Kyiv", lat: 49.84, lon: 24.03, rank: 2, region: "Europe" },
  { id: "odessa", name: "Odesa", country: "Ukraine", tz: "Europe/Kyiv", lat: 46.48, lon: 30.73, rank: 2, region: "Europe" },
  { id: "kharkiv", name: "Kharkiv", country: "Ukraine", tz: "Europe/Kyiv", lat: 49.99, lon: 36.23, rank: 2, region: "Europe" },
  { id: "dnipro", name: "Dnipro", country: "Ukraine", tz: "Europe/Kyiv", lat: 48.46, lon: 35.04, rank: 3, region: "Europe" },
  { id: "kaunas", name: "Kaunas", country: "Lithuania", tz: "Europe/Vilnius", lat: 54.9, lon: 23.9, rank: 4, region: "Europe" },
  { id: "akureyri", name: "Akureyri", country: "Iceland", tz: "Atlantic/Reykjavik", lat: 65.68, lon: -18.09, rank: 4, region: "Europe" },

  // ---------- Africa ----------
  { id: "alexandria", name: "Alexandria", country: "Egypt", tz: "Africa/Cairo", lat: 31.2, lon: 29.92, rank: 2, region: "Africa" },
  { id: "giza", name: "Giza", country: "Egypt", tz: "Africa/Cairo", lat: 30.01, lon: 31.21, rank: 3, region: "Africa" },
  { id: "luxor", name: "Luxor", country: "Egypt", tz: "Africa/Cairo", lat: 25.69, lon: 32.64, rank: 3, region: "Africa" },
  { id: "casablanca", name: "Casablanca", country: "Morocco", tz: "Africa/Casablanca", lat: 33.57, lon: -7.59, rank: 2, region: "Africa" },
  { id: "marrakesh", name: "Marrakesh", country: "Morocco", tz: "Africa/Casablanca", lat: 31.63, lon: -8.0, rank: 2, region: "Africa" },
  { id: "fez", name: "Fez", country: "Morocco", tz: "Africa/Casablanca", lat: 34.02, lon: -5.0, rank: 3, region: "Africa" },
  { id: "tangier", name: "Tangier", country: "Morocco", tz: "Africa/Casablanca", lat: 35.76, lon: -5.83, rank: 3, region: "Africa" },
  { id: "oran", name: "Oran", country: "Algeria", tz: "Africa/Algiers", lat: 35.7, lon: -0.63, rank: 2, region: "Africa" },
  { id: "constantine", name: "Constantine", country: "Algeria", tz: "Africa/Algiers", lat: 36.37, lon: 6.61, rank: 3, region: "Africa" },
  { id: "sfax", name: "Sfax", country: "Tunisia", tz: "Africa/Tunis", lat: 34.74, lon: 10.76, rank: 3, region: "Africa" },
  { id: "benghazi", name: "Benghazi", country: "Libya", tz: "Africa/Tripoli", lat: 32.12, lon: 20.07, rank: 3, region: "Africa" },
  { id: "port_sudan", name: "Port Sudan", country: "Sudan", tz: "Africa/Khartoum", lat: 19.62, lon: 37.22, rank: 4, region: "Africa" },
  { id: "dire_dawa", name: "Dire Dawa", country: "Ethiopia", tz: "Africa/Addis_Ababa", lat: 9.59, lon: 41.87, rank: 4, region: "Africa" },
  { id: "mombasa", name: "Mombasa", country: "Kenya", tz: "Africa/Nairobi", lat: -4.04, lon: 39.67, rank: 2, region: "Africa" },
  { id: "kisumu", name: "Kisumu", country: "Kenya", tz: "Africa/Nairobi", lat: -0.09, lon: 34.77, rank: 4, region: "Africa" },
  { id: "dar_es_salaam", name: "Dar es Salaam", country: "Tanzania", tz: "Africa/Dar_es_Salaam", lat: -6.79, lon: 39.21, rank: 2, region: "Africa" },
  { id: "arusha", name: "Arusha", country: "Tanzania", tz: "Africa/Dar_es_Salaam", lat: -3.39, lon: 36.68, rank: 3, region: "Africa" },
  { id: "entebbe", name: "Entebbe", country: "Uganda", tz: "Africa/Kampala", lat: 0.06, lon: 32.46, rank: 4, region: "Africa" },
  { id: "kano", name: "Kano", country: "Nigeria", tz: "Africa/Lagos", lat: 12.0, lon: 8.52, rank: 2, region: "Africa" },
  { id: "ibadan", name: "Ibadan", country: "Nigeria", tz: "Africa/Lagos", lat: 7.38, lon: 3.9, rank: 2, region: "Africa" },
  { id: "port_harcourt", name: "Port Harcourt", country: "Nigeria", tz: "Africa/Lagos", lat: 4.82, lon: 7.05, rank: 3, region: "Africa" },
  { id: "kumasi", name: "Kumasi", country: "Ghana", tz: "Africa/Accra", lat: 6.69, lon: -1.62, rank: 3, region: "Africa" },
  { id: "tamale", name: "Tamale", country: "Ghana", tz: "Africa/Accra", lat: 9.4, lon: -0.84, rank: 4, region: "Africa" },
  { id: "yamoussoukro", name: "Yamoussoukro", country: "Côte d'Ivoire", tz: "Africa/Abidjan", lat: 6.82, lon: -5.28, rank: 3, region: "Africa", capital: true },
  { id: "bouake", name: "Bouaké", country: "Côte d'Ivoire", tz: "Africa/Abidjan", lat: 7.69, lon: -5.03, rank: 4, region: "Africa" },
  { id: "douala", name: "Douala", country: "Cameroon", tz: "Africa/Douala", lat: 4.05, lon: 9.7, rank: 2, region: "Africa" },
  { id: "lubumbashi", name: "Lubumbashi", country: "DR Congo", tz: "Africa/Lubumbashi", lat: -11.66, lon: 27.48, rank: 3, region: "Africa" },
  { id: "goma", name: "Goma", country: "DR Congo", tz: "Africa/Lubumbashi", lat: -1.68, lon: 29.23, rank: 4, region: "Africa" },
  { id: "pointe_noire", name: "Pointe-Noire", country: "Congo", tz: "Africa/Brazzaville", lat: -4.78, lon: 11.86, rank: 3, region: "Africa" },
  { id: "benguela", name: "Benguela", country: "Angola", tz: "Africa/Luanda", lat: -12.58, lon: 13.41, rank: 3, region: "Africa" },
  { id: "durban", name: "Durban", country: "South Africa", tz: "Africa/Johannesburg", lat: -29.86, lon: 31.03, rank: 2, region: "Africa" },
  { id: "port_elizabeth", name: "Gqeberha", country: "South Africa", tz: "Africa/Johannesburg", lat: -33.96, lon: 25.6, rank: 3, region: "Africa" },
  { id: "bloemfontein", name: "Bloemfontein", country: "South Africa", tz: "Africa/Johannesburg", lat: -29.12, lon: 26.22, rank: 3, region: "Africa" },
  { id: "beira", name: "Beira", country: "Mozambique", tz: "Africa/Maputo", lat: -19.84, lon: 34.84, rank: 3, region: "Africa" },
  { id: "toamasina", name: "Toamasina", country: "Madagascar", tz: "Indian/Antananarivo", lat: -18.15, lon: 49.4, rank: 4, region: "Africa" },

  // ---------- Middle East & Asia ----------
  { id: "abu_dhabi", name: "Abu Dhabi", country: "UAE", tz: "Asia/Dubai", lat: 24.45, lon: 54.38, rank: 2, region: "Asia", capital: true },
  { id: "sharjah", name: "Sharjah", country: "UAE", tz: "Asia/Dubai", lat: 25.35, lon: 55.4, rank: 3, region: "Asia" },
  { id: "jeddah", name: "Jeddah", country: "Saudi Arabia", tz: "Asia/Riyadh", lat: 21.49, lon: 39.19, rank: 2, region: "Asia" },
  { id: "mecca", name: "Mecca", country: "Saudi Arabia", tz: "Asia/Riyadh", lat: 21.39, lon: 39.86, rank: 2, region: "Asia" },
  { id: "medina", name: "Medina", country: "Saudi Arabia", tz: "Asia/Riyadh", lat: 24.47, lon: 39.61, rank: 2, region: "Asia" },
  { id: "dammam", name: "Dammam", country: "Saudi Arabia", tz: "Asia/Riyadh", lat: 26.43, lon: 50.1, rank: 3, region: "Asia" },
  { id: "mashhad", name: "Mashhad", country: "Iran", tz: "Asia/Tehran", lat: 36.26, lon: 59.62, rank: 2, region: "Asia" },
  { id: "isfahan", name: "Isfahan", country: "Iran", tz: "Asia/Tehran", lat: 32.65, lon: 51.67, rank: 2, region: "Asia" },
  { id: "shiraz", name: "Shiraz", country: "Iran", tz: "Asia/Tehran", lat: 29.61, lon: 52.53, rank: 3, region: "Asia" },
  { id: "tabriz", name: "Tabriz", country: "Iran", tz: "Asia/Tehran", lat: 38.08, lon: 46.29, rank: 3, region: "Asia" },
  { id: "lahore", name: "Lahore", country: "Pakistan", tz: "Asia/Karachi", lat: 31.55, lon: 74.34, rank: 2, region: "Asia" },
  { id: "peshawar", name: "Peshawar", country: "Pakistan", tz: "Asia/Karachi", lat: 34.02, lon: 71.58, rank: 3, region: "Asia" },
  { id: "faisalabad", name: "Faisalabad", country: "Pakistan", tz: "Asia/Karachi", lat: 31.42, lon: 73.08, rank: 3, region: "Asia" },
  { id: "bangalore", name: "Bengaluru", country: "India", tz: "Asia/Kolkata", lat: 12.97, lon: 77.59, rank: 1, region: "Asia" },
  { id: "hyderabad_in", name: "Hyderabad", country: "India", tz: "Asia/Kolkata", lat: 17.39, lon: 78.49, rank: 1, region: "Asia" },
  { id: "chennai", name: "Chennai", country: "India", tz: "Asia/Kolkata", lat: 13.08, lon: 80.27, rank: 1, region: "Asia" },
  { id: "kolkata", name: "Kolkata", country: "India", tz: "Asia/Kolkata", lat: 22.57, lon: 88.36, rank: 1, region: "Asia" },
  { id: "pune", name: "Pune", country: "India", tz: "Asia/Kolkata", lat: 18.52, lon: 73.86, rank: 2, region: "Asia" },
  { id: "ahmedabad", name: "Ahmedabad", country: "India", tz: "Asia/Kolkata", lat: 23.02, lon: 72.57, rank: 2, region: "Asia" },
  { id: "jaipur", name: "Jaipur", country: "India", tz: "Asia/Kolkata", lat: 26.91, lon: 75.79, rank: 2, region: "Asia" },
  { id: "lucknow", name: "Lucknow", country: "India", tz: "Asia/Kolkata", lat: 26.85, lon: 80.95, rank: 2, region: "Asia" },
  { id: "chittagong", name: "Chittagong", country: "Bangladesh", tz: "Asia/Dhaka", lat: 22.36, lon: 91.8, rank: 2, region: "Asia" },
  { id: "khulna", name: "Khulna", country: "Bangladesh", tz: "Asia/Dhaka", lat: 22.85, lon: 89.54, rank: 3, region: "Asia" },
  { id: "chiang_mai", name: "Chiang Mai", country: "Thailand", tz: "Asia/Bangkok", lat: 18.79, lon: 98.98, rank: 2, region: "Asia" },
  { id: "phuket", name: "Phuket", country: "Thailand", tz: "Asia/Bangkok", lat: 7.88, lon: 98.39, rank: 3, region: "Asia" },
  { id: "pattaya", name: "Pattaya", country: "Thailand", tz: "Asia/Bangkok", lat: 12.93, lon: 100.88, rank: 3, region: "Asia" },
  { id: "surabaya", name: "Surabaya", country: "Indonesia", tz: "Asia/Jakarta", lat: -7.26, lon: 112.75, rank: 2, region: "Asia" },
  { id: "bandung", name: "Bandung", country: "Indonesia", tz: "Asia/Jakarta", lat: -6.92, lon: 107.61, rank: 2, region: "Asia" },
  { id: "medan", name: "Medan", country: "Indonesia", tz: "Asia/Jakarta", lat: 3.6, lon: 98.67, rank: 2, region: "Asia" },
  { id: "denpasar", name: "Denpasar", country: "Indonesia", tz: "Asia/Makassar", lat: -8.67, lon: 115.21, rank: 2, region: "Asia" },
  { id: "makassar", name: "Makassar", country: "Indonesia", tz: "Asia/Makassar", lat: -5.14, lon: 119.42, rank: 3, region: "Asia" },
  { id: "guangzhou", name: "Guangzhou", country: "China", tz: "Asia/Shanghai", lat: 23.13, lon: 113.26, rank: 1, region: "Asia" },
  { id: "shenzhen", name: "Shenzhen", country: "China", tz: "Asia/Shanghai", lat: 22.54, lon: 114.06, rank: 1, region: "Asia" },
  { id: "chengdu", name: "Chengdu", country: "China", tz: "Asia/Shanghai", lat: 30.57, lon: 104.07, rank: 1, region: "Asia" },
  { id: "wuhan", name: "Wuhan", country: "China", tz: "Asia/Shanghai", lat: 30.59, lon: 114.31, rank: 2, region: "Asia" },
  { id: "xian", name: "Xi'an", country: "China", tz: "Asia/Shanghai", lat: 34.34, lon: 108.94, rank: 2, region: "Asia" },
  { id: "hangzhou", name: "Hangzhou", country: "China", tz: "Asia/Shanghai", lat: 30.27, lon: 120.16, rank: 2, region: "Asia" },
  { id: "nanjing", name: "Nanjing", country: "China", tz: "Asia/Shanghai", lat: 32.06, lon: 118.8, rank: 2, region: "Asia" },
  { id: "chongqing", name: "Chongqing", country: "China", tz: "Asia/Shanghai", lat: 29.56, lon: 106.55, rank: 1, region: "Asia" },
  { id: "tianjin", name: "Tianjin", country: "China", tz: "Asia/Shanghai", lat: 39.13, lon: 117.2, rank: 2, region: "Asia" },
  { id: "kaohsiung", name: "Kaohsiung", country: "Taiwan", tz: "Asia/Taipei", lat: 22.63, lon: 120.3, rank: 2, region: "Asia" },
  { id: "taichung", name: "Taichung", country: "Taiwan", tz: "Asia/Taipei", lat: 24.15, lon: 120.67, rank: 3, region: "Asia" },
  { id: "busan", name: "Busan", country: "South Korea", tz: "Asia/Seoul", lat: 35.18, lon: 129.08, rank: 1, region: "Asia" },
  { id: "incheon", name: "Incheon", country: "South Korea", tz: "Asia/Seoul", lat: 37.46, lon: 126.71, rank: 2, region: "Asia" },
  { id: "daegu", name: "Daegu", country: "South Korea", tz: "Asia/Seoul", lat: 35.87, lon: 128.6, rank: 2, region: "Asia" },
  { id: "nagoya", name: "Nagoya", country: "Japan", tz: "Asia/Tokyo", lat: 35.18, lon: 136.91, rank: 2, region: "Asia" },
  { id: "sapporo", name: "Sapporo", country: "Japan", tz: "Asia/Tokyo", lat: 43.06, lon: 141.35, rank: 2, region: "Asia" },
  { id: "fukuoka", name: "Fukuoka", country: "Japan", tz: "Asia/Tokyo", lat: 33.59, lon: 130.4, rank: 2, region: "Asia" },
  { id: "kyoto", name: "Kyoto", country: "Japan", tz: "Asia/Tokyo", lat: 35.01, lon: 135.77, rank: 2, region: "Asia" },
  { id: "yokohama", name: "Yokohama", country: "Japan", tz: "Asia/Tokyo", lat: 35.44, lon: 139.64, rank: 2, region: "Asia" },
  { id: "kobe", name: "Kobe", country: "Japan", tz: "Asia/Tokyo", lat: 34.69, lon: 135.2, rank: 3, region: "Asia" },
  { id: "cebu", name: "Cebu", country: "Philippines", tz: "Asia/Manila", lat: 10.32, lon: 123.89, rank: 2, region: "Asia" },
  { id: "davao", name: "Davao", country: "Philippines", tz: "Asia/Manila", lat: 7.19, lon: 125.46, rank: 2, region: "Asia" },
  { id: "quezon_city", name: "Quezon City", country: "Philippines", tz: "Asia/Manila", lat: 14.68, lon: 121.04, rank: 2, region: "Asia" },
  { id: "georgetown_my", name: "George Town", country: "Malaysia", tz: "Asia/Kuala_Lumpur", lat: 5.42, lon: 100.33, rank: 3, region: "Asia" },
  { id: "johor_bahru", name: "Johor Bahru", country: "Malaysia", tz: "Asia/Kuala_Lumpur", lat: 1.49, lon: 103.74, rank: 2, region: "Asia" },
  { id: "kota_kinabalu", name: "Kota Kinabalu", country: "Malaysia", tz: "Asia/Kuching", lat: 5.98, lon: 116.07, rank: 3, region: "Asia" },
  { id: "da_nang", name: "Da Nang", country: "Vietnam", tz: "Asia/Ho_Chi_Minh", lat: 16.05, lon: 108.2, rank: 2, region: "Asia" },
  { id: "hai_phong", name: "Hai Phong", country: "Vietnam", tz: "Asia/Ho_Chi_Minh", lat: 20.84, lon: 106.69, rank: 3, region: "Asia" },
  { id: "mandalay", name: "Mandalay", country: "Myanmar", tz: "Asia/Yangon", lat: 21.96, lon: 96.09, rank: 3, region: "Asia" },
  { id: "siem_reap", name: "Siem Reap", country: "Cambodia", tz: "Asia/Phnom_Penh", lat: 13.36, lon: 103.86, rank: 3, region: "Asia" },
  { id: "luang_prabang", name: "Luang Prabang", country: "Laos", tz: "Asia/Vientiane", lat: 19.89, lon: 102.14, rank: 4, region: "Asia" },
  { id: "kandy", name: "Kandy", country: "Sri Lanka", tz: "Asia/Colombo", lat: 7.29, lon: 80.63, rank: 3, region: "Asia" },
  { id: "galle", name: "Galle", country: "Sri Lanka", tz: "Asia/Colombo", lat: 6.03, lon: 80.22, rank: 4, region: "Asia" },
  { id: "pokhara", name: "Pokhara", country: "Nepal", tz: "Asia/Kathmandu", lat: 28.21, lon: 83.99, rank: 3, region: "Asia" },
  { id: "haifa", name: "Haifa", country: "Israel", tz: "Asia/Jerusalem", lat: 32.79, lon: 34.99, rank: 3, region: "Asia" },
  { id: "tel_aviv", name: "Tel Aviv", country: "Israel", tz: "Asia/Jerusalem", lat: 32.09, lon: 34.78, rank: 2, region: "Asia" },
  { id: "erbil", name: "Erbil", country: "Iraq", tz: "Asia/Baghdad", lat: 36.19, lon: 44.01, rank: 3, region: "Asia" },
  { id: "basra", name: "Basra", country: "Iraq", tz: "Asia/Baghdad", lat: 30.51, lon: 47.78, rank: 3, region: "Asia" },
  { id: "aleppo", name: "Aleppo", country: "Syria", tz: "Asia/Damascus", lat: 36.2, lon: 37.16, rank: 3, region: "Asia" },
  { id: "samarkand", name: "Samarkand", country: "Uzbekistan", tz: "Asia/Samarkand", lat: 39.65, lon: 66.96, rank: 3, region: "Asia" },
  { id: "bukhara", name: "Bukhara", country: "Uzbekistan", tz: "Asia/Samarkand", lat: 39.77, lon: 64.42, rank: 4, region: "Asia" },

  // ---------- Oceania ----------
  { id: "gold_coast", name: "Gold Coast", country: "Australia", tz: "Australia/Brisbane", lat: -28.02, lon: 153.4, rank: 3, region: "Oceania" },
  { id: "darwin", name: "Darwin", country: "Australia", tz: "Australia/Darwin", lat: -12.46, lon: 130.84, rank: 3, region: "Oceania" },
  { id: "cairns", name: "Cairns", country: "Australia", tz: "Australia/Brisbane", lat: -16.92, lon: 145.78, rank: 3, region: "Oceania" },
  { id: "christchurch", name: "Christchurch", country: "New Zealand", tz: "Pacific/Auckland", lat: -43.53, lon: 172.64, rank: 2, region: "Oceania" },
  { id: "queenstown", name: "Queenstown", country: "New Zealand", tz: "Pacific/Auckland", lat: -45.03, lon: 168.66, rank: 3, region: "Oceania" },
  { id: "hamilton_nz", name: "Hamilton", country: "New Zealand", tz: "Pacific/Auckland", lat: -37.79, lon: 175.28, rank: 3, region: "Oceania" },
  { id: "lae", name: "Lae", country: "Papua New Guinea", tz: "Pacific/Port_Moresby", lat: -6.72, lon: 146.99, rank: 4, region: "Oceania" },
];
